version: '3.8'
services:
  traefik:
    image: traefik:v3.0
    command:
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --api.dashboard=true
      - --providers.docker.exposedbydefault=false
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portfolio_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
  front:
    container_name: portefolio-front
    build:
        context: .
        dockerfile: Docker/Dockerfile.front
    restart: unless-stopped
    networks:
      - portfolio_net
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`portfolio.localhost`)"
      - "traefik.http.routers.portfolio.entrypoints=web"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"


volumes:
  db_data:

networks:
  portfolio_net:
    driver: bridge
