services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    container_name: traefik
    command:
      - '--api.dashboard=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.letsencrypt.acme.email=contact@maximelapouge.fr'
      - '--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web'

    ports:
      - '80:80'
      - '443:443'
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - portfolio-proxy

  front:
    container_name: front
    build:
      context: .
      dockerfile: Docker/dockerfile.prod.front

    restart: unless-stopped

    networks:
      - portfolio-proxy
      - portfolio-internal

    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.front.rule=Host(`maximelapouge.fr`)'
      - 'traefik.http.routers.front.entrypoints=websecure'
      - 'traefik.http.routers.front.tls=true'
      - 'traefik.http.routers.front.tls.certresolver=letsencrypt'
      - 'traefik.http.services.front.loadbalancer.server.port=80'

  back:
    container_name: back
    build:
      context: .
      dockerfile: ./Docker/dockerfile.prod.api
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://db:27017/portfolio
      FRONTEND_URL: https://maximelapouge.fr
    networks:
      - portfolio-proxy
      - portfolio-internal
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.back-secure.rule=Host(`api.maximelapouge.fr`)'
      - 'traefik.http.routers.back-secure.entrypoints=websecure'
      - 'traefik.http.routers.back-secure.tls=true'
      - 'traefik.http.routers.back.tls.certresolver=letsencrypt'
      - 'traefik.http.services.back.loadbalancer.server.port=3100'

  db:
    container_name: db
    image: mongo:latest
    restart: unless-stopped
    networks:
      - portfolio-internal
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  letsencrypt:
networks:
  portfolio-proxy:
    external: true
  portfolio-internal:
    external: false
