version: '1.0.0'
services:
  web:
    build:
        image: moxii/portefolio/front:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - site_net
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  api:
    build:
      image : moxii/portefolio/api:latest
    restart: always
    volumes:
      - ./api:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - site_net
      - db_net
    environment:
      - MYSQL_DATABASE=portefolio
      - MYSQL_USER=portefolio
      - MYSQL_PASSWORD=portefolio
      - MYSQL_HOST=db
      - DATABASE_URL=mysql://portefolio:portefolio@db:3306/portefolio
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    networks:
      - db_net
    expose:
    ports :
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=portefolio
      - MYSQL_USER=portefolio
      - MYSQL_ROOT_PASSWORD=portefolio
      - MY_SQL_PASSWORD=portefolio
volumes:
  db_data:

networks:
  db_net:
  site_net:
