FROM node:20 as builder
WORKDIR /app
COPY . .
RUN npm install && npm run build

FROM node:20 as runner
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./
RUN npm install
EXPOSE 4173
CMD ["npm", "run", "preview"]
