FROM node:26 as builder
WORKDIR /app

COPY api/package*.json ./

RUN npm ci

FROM node:26-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY api/ ./api/

EXPOSE 3100

CMD ["npm", "start"]