FROM node:23-alpine
WORKDIR /app
COPY package.json ./
RUN npm install -g npm@latest
RUN npm install -g esbuild@0.18.20
RUN apk add --no-cache \
    python3 \
    py3-pip \
    build-base
RUN npm install
COPY ./src .
COPY ./public .
COPY ./index.html .
COPY ./vite.config.js .
EXPOSE 5173
CMD ["npm" , "run" , "dev","--host" , "0.0.0.0"]