FROM node:26 as builder

WORKDIR /app

COPY front/package*.json ./

run npm ci
COPY front/ .

RUN npm run build 

from nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./Docker/nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]