FROM node:26 AS builder

WORKDIR /app

COPY front/package*.json ./

RUN npm ci

FROM node:26
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules

COPY front/public ./public
COPY front/src ./src
COPY front/.eslintrc.cjs ./
COPY front/index.html ./
COPY front/jsconfig.json ./
COPY front/vite.config.js ./

EXPOSE 5173
CMD ["npm","run","dev"]