FROM node:26 as builder

WORKDIR /app

COPY front/package*.json ./

RUN npm ci
COPY front/ .

RUN npm run build 

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./Docker/ngnix/default.conf /etc/ngnix/conf.d/default.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]