FROM node:26 AS builder
WORKDIR /app/api

COPY api/package*.json ./

RUN npm ci 
COPY api/ ./
RUN npm run build

FROM node:26-alpine

WORKDIR /app/api
COPY --from=builder /app/api/package*.json ./
COPY --from=builder /app/api/node_modules ./node_modules
COPY --from=builder /app/api/dist ./dist

EXPOSE 3100

CMD ["node", "dist/server.js"]