FROM node:26 as builder
WORKDIR /app/api

COPY api/package*.json ./

RUN npm ci

FROM node:26-alpine

WORKDIR /app/api

COPY --from=builder /app/api/node_modules ./node_modules
COPY api/ ./

EXPOSE 3100

CMD ["npm", "start"]