FROM node:20 as builder
WORKDIR /app
COPY . .
RUN npm install && npm run build

FROM node:20-alpine as runner
WORKDIR /app
COPY --from=builder /app/dist ./dist
RUN npm install -g serve
EXPOSE 4173
CMD ["serve", "-s", "dist", "-l", "4173"]
