FROM node:23-alpine
RUN npm install -g nodemon
RUN apk add --no-cache \
    python3 \
    py3-pip \
    make \
    g++ \
    gcc
WORKDIR /app/api
COPY ./api/package.json ./
RUN npm install
RUN npm install -g
COPY ./api .
EXPOSE 3000
CMD ["nodemon" , "./server.js" , "rs"]