name: Deploy with dock
run-name: ${{ github.actor }} is 🚀 deploy website on push
on:
  push:
    branches:
      - prod
jobs:
  deploy_ssh:
    environment: SECRET
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on server
        run: |
          ssh -o StrictHostKeyChecking=no \
            ${{ secrets.USER }}@${{ secrets.SERVER_IP }} \
            "/home/${{ secrets.USER }}/infra/deploy.sh portfolio git@github:Moxiii/portefolio.git"
