name: Deploy with dock
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    environment: SECRET
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Add SSH Key
        id : ssh_keygen
        run: |
          ssh-keygen -t rsa -b 4096 -C "github-action" -f $HOME/.ssh/id_rsa -N ""
          echo "::set-output name= public_key::$cat"($HOME/ .ssh/id_rsa.pub)" 

      - name : Add pub key to serv
        run: |
          echo "${{ steps.ssh_keygen.outputs.public_key }}" | ssh -o StrictHostKeyChecking=no moxi@${{ secrets.SERVER_IP }} 'cat >> ~/.ssh/authorized_keys'
        

      - name : Deploy to serv
        run: |
          ssh moxi@${{ secrets.SERVER_IP }} 'cd ./Docker/compose.yaml && docker-compose pull && docker-compose up -d'
