name: Deploy with dock
run-name: ${{ github.actor }} is 🚀 deploy website on push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy_ssh:
    environment: SECRET
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Set Up SSH key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          
      - name  : Rsync project to server
        run : | 
          sshpass -p "${{ secrets.SSH_PSWD }}" rsync -avz -e "ssh -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no" ./ ubuntu@${{ secrets.SERVER_IP }}:/home/ubuntu/portfolio/
          

      - name : Deploy with docker-compose
        run: |
          ssh -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
          cd /home/ubuntu/portfolio
          docker-compose pull 
          docker-compose up -d --build
          EOF

      - name : cleanup
        run: | 
          rm -rf $HOME/.ssh/id_rsa
  deploy_ftp:
    if:  false
    environment: SECRET
    name : 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name : 🔧 Install dependencies and build
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name : 🔧 Install dependencies
        run: npm install


      - name : 🔧 Build
        run: |
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-DEPLOY-Action@v4.3.4
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          local-dir: dist/
          server-dir: www/
          dangerous-clean-slate: false

