name: Deploy with dock
run-name: ${{ github.actor }} is 🚀 deploy website on push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy_ssh:
    if: ${{false}}
    environment: SECRET
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Logging to DockerHub
        uses: docker/login-action@v3
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name : Build and push API
        run : | 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/portefolio:api -f api/Dockerfile ./api
          docker push ${{ secrets.DOCKER_USERNAME }}/portefolio:api

      - name: Build and push Front
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/portefolio:front -f Docker/Dockerfile ./
          docker push ${{ secrets.DOCKER_USERNAME }}/portefolio:front

      - name: Set Up SSH key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          

      - name : Deploy to serv
        run: |
          ssh -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no moxi@${{ secrets.SERVER_IP }} 'cd ./Docker/compose.yaml && docker-compose pull && docker-compose up -d'

      - name : cleanup
        run: | 
          rm rf $HOME/ .ssh/id_rsa
  deploy_ftp:
    environment: SECRET
    name : 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name : 🔧 Install dependencies and build
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name : 🔧 Install dependencies
        run: |
         npm install

      - name : 🔧 Build
        run: |
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-DEPLOY-Action@v4.3.4
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          local-dir: dist
          server-dir: www
          delete: true