name: Deploy with dock
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    environment: SECRET
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Logging to DockerHub
        uses: docker/login-action@v3
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name : Build and push API
        run : | 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/portefolio:api -f api/Dockerfile ./api
          docker push ${{ secrets.DOCKER_USERNAME }}/portefolio:api

      - name: Build and push Front
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/portefolio:front -f Docker/Dockerfile ./
          docker push ${{ secrets.DOCKER_USERNAME }}/portefolio:front

      - name: Add SSH Key
        id : ssh_keygen
        run: |
          ssh-keygen - t rsa -b 4096 -C "github-action" -f $HOME/ .ssh/id_rsa -n ""
          echo "::set-output name= public_key::$cat"($HOME/ .ssh/id_rsa.pub)" 

      - name : Add pub key to serv
        run: |
          echo "${{ steps.ssh_keygen.outputs.public_key }}" | ssh -o StrictHostKeyChecking=no moxi@${{ secrets.SERVER_IP }} 'cat >> ~/.ssh/authorized_keys'
        

      - name : Deploy to serv
        run: |
          ssh moxi@${{ secrets.SERVER_IP }} 'cd ./Docker/compose.yaml && docker-compose pull && docker-compose up -d'
